Repository CCExtractor/ultimate_alarm_clock, pull requests merged in 2023-09, with the labels that each got.

#45 bug fix
  lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
Labels: bug, good first issue

#50 added the off text on the label tile when the label is empty
  lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
Labels: bug, enhancement

#43 Feat: Implementing the Haptic Feedback
  lib/app/data/providers/secure_storage_provider.dart
  lib/app/modules/addOrUpdateAlarm/bindings/add_or_update_alarm_binding.dart
  lib/app/modules/addOrUpdateAlarm/views/add_or_update_alarm_view.dart
  lib/app/modules/addOrUpdateAlarm/views/alarm_id_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/alarm_offset_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/label_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/location_activity_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/maths_challenge_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/qr_bar_code_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/repeat_once_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/repeat_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/screen_activity_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/shake_to_dismiss_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/shared_alarm_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/shared_users_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/snooze_duration_tile.dart
  lib/app/modules/addOrUpdateAlarm/views/weather_tile.dart
  lib/app/modules/alarmChallenge/bindings/alarm_challenge_binding.dart
  lib/app/modules/alarmChallenge/views/alarm_challenge_view.dart
  lib/app/modules/alarmChallenge/views/maths_challenge_view.dart
  lib/app/modules/alarmChallenge/views/qr_challenge_view.dart
  lib/app/modules/alarmChallenge/views/shake_challenge_view.dart
  lib/app/modules/alarmRing/bindings/alarm_ring_binding.dart
  lib/app/modules/alarmRing/views/alarm_ring_view.dart
  lib/app/modules/alarmRingIgnore/bindings/alarm_ring_ignore_binding.dart
  lib/app/modules/alarmRingIgnore/views/alarm_ring_ignore_view.dart
  lib/app/modules/home/bindings/home_binding.dart
  lib/app/modules/home/views/home_view.dart
  lib/app/modules/settings/controllers/settings_controller.dart
  lib/app/modules/settings/views/enable_haptic_feedback.dart
  lib/app/modules/settings/views/google_sign_in.dart
  lib/app/modules/settings/views/settings_view.dart
  lib/app/modules/settings/views/weather_api.dart
  lib/app/routes/app_pages.dart
  lib/app/utils/utils.dart
  pubspec.lock
Labels: enhancement, feat

#47 fixes#46
  lib/app/modules/home/views/home_view.dart
Labels: feat
